/* generated by l1trans */
#include "mixa_manager/mixa_console_window.lm1.h"
#include "mixa_manager/mixa_file.h"
int mixa_console_read_window(MixaFile * file, size_t offset, char * dest, size_t capacity, size_t * got)
{
    size_t accumulated;
    size_t chunk_read;
    size_t remaining;
    int rc;
    if (got == 0) {
    return MIXA_FILE_ERR_ARG;
    }
    got[0] = 0;
    accumulated = 0;
    if (file == 0) {
    return MIXA_FILE_ERR_ARG;
    }
    if (capacity == 0) {
    return MIXA_FILE_OK;
    }
    if (dest == 0) {
    return MIXA_FILE_ERR_ARG;
    }
    rc = mixa_file_seek(file, offset);
    if (rc != MIXA_FILE_OK) {
    got[0] = accumulated;
    return rc;
    }
    remaining = capacity;
    while (remaining > 0) {
    chunk_read = 0;
    rc = mixa_file_read(file, dest + accumulated, remaining, &chunk_read);
    accumulated = accumulated + chunk_read;
    got[0] = accumulated;
    if (rc != MIXA_FILE_OK) {
    return rc;
    }
    if (chunk_read == 0) {
    return MIXA_FILE_OK;
    }
    remaining = remaining - chunk_read;
    }
    return MIXA_FILE_OK;
}
