/* generated by l1trans */
#include "mixa_manager/mixa_console_window.lm1.h"
#include "mixa_manager/mixa_file.h"
int mixa_console_read_window(MixaFile * file, size_t offset, char * dest, size_t capacity, size_t * got)
{
    size_t accumulated;
    size_t chunk_read;
    size_t remaining;
    int rc;
    if (got == 0) {
    return MIXA_FILE_ERR_ARG;
    }
    got[0] = 0;
    accumulated = 0;
    if (file == 0) {
    return MIXA_FILE_ERR_ARG;
    }
    if (capacity == 0) {
    return MIXA_FILE_OK;
    }
    if (dest == 0) {
    return MIXA_FILE_ERR_ARG;
    }
    rc = mixa_file_seek(file, offset);
    if (rc != MIXA_FILE_OK) {
    got[0] = accumulated;
    return rc;
    }
    remaining = capacity;
    while (remaining > 0) {
    chunk_read = 0;
    rc = mixa_file_read(file, dest + accumulated, remaining, &chunk_read);
    accumulated = accumulated + chunk_read;
    got[0] = accumulated;
    if (rc != MIXA_FILE_OK) {
    return rc;
    }
    if (chunk_read == 0) {
    return MIXA_FILE_OK;
    }
    remaining = remaining - chunk_read;
    }
    return MIXA_FILE_OK;
}
#include <stdio.h>
#include <string.h>
int main(int argc, char * * argv)
{
    MixaFile * testfile;
    unsigned buf[16];
    size_t got;
    int rc;
    char * fixture_path;
    testfile = 0;
    got = 0;
    fixture_path = "mixa_console_window_fixture.bin";
    if (argc > 1) {
    fixture_path = argv[1];
    }
    rc = mixa_file_open(&testfile, fixture_path, MIXA_FILE_MODE_READ);
    if (rc != MIXA_FILE_OK) {
    printf("FAILED: open rc=%d\n", rc);
    return 1;
    }
    memset(buf, 0xAA, 16U);
    got = 0xDEADBEEF;
    rc = mixa_console_read_window(testfile, 0U, buf, 8U, &got);
    if (rc != MIXA_FILE_OK) {
    printf("FAILED: read rc=%d\n", rc);
    mixa_file_close(testfile);
    return 1;
    }
    if (got != 8U) {
    printf("FAILED: got=%zu expected 8\n", got);
    mixa_file_close(testfile);
    return 1;
    }
    if (memcmp(buf, "FIXTURE0", 8U) != 0) {
    printf("FAILED: memcmp mismatch\n");
    mixa_file_close(testfile);
    return 1;
    }
    if (buf[8] != 0xAA) {
    printf("FAILED: guard byte changed\n");
    mixa_file_close(testfile);
    return 1;
    }
    mixa_file_close(testfile);
    printf("PASS: 1 case 5 checks\n");
    return 0;
}
