#ifndef LM_TEST_TRANS_L4_FORWARD_SOURCE_ROWS_SUPPORT_H
#define LM_TEST_TRANS_L4_FORWARD_SOURCE_ROWS_SUPPORT_H

extern LmTestForwardStruct *lm_test_forward_struct_type;
extern struct LmTestForwardStruct *lm_test_forward_struct_type;
extern LmTestForwardUnion *lm_test_forward_union_type;
extern union LmTestForwardUnion *lm_test_forward_union_type;
extern LmTestForwardDuplicate *lm_test_forward_duplicate_type;
extern union LmTestForwardDuplicate *lm_test_forward_duplicate_type;
extern LmTestForwardLateNone *lm_test_forward_late_none_type;
extern struct LmTestForwardLateNone *lm_test_forward_late_none_type;
extern LmTestForwardAfterOther *lm_test_forward_after_other_type;
extern struct LmTestForwardAfterOther *lm_test_forward_after_other_type;
extern LmTestForwardJoined *lm_test_forward_joined_type;
extern struct LmTestForwardJoined *lm_test_forward_joined_type;
extern LmTestForwardSchemaFallback *lm_test_forward_schema_fallback_type;
extern struct LmTestForwardSchemaFallback *lm_test_forward_schema_fallback_type;
extern LmTestForwardLayout *lm_test_forward_layout_type;
extern struct LmTestForwardLayout *lm_test_forward_layout_type;
typedef int LmTestForwardNone;

extern LmTestForwardWideStruct *lm_test_forward_wide_struct_type;
extern struct LmTestForwardWideStruct *lm_test_forward_wide_struct_type;
extern LmTestForwardWideUnion *lm_test_forward_wide_union_type;
extern union LmTestForwardWideUnion *lm_test_forward_wide_union_type;
extern LmTestForwardWideDuplicate *lm_test_forward_wide_duplicate_type;
extern union LmTestForwardWideDuplicate *lm_test_forward_wide_duplicate_type;
extern LmTestForwardWideLateNone *lm_test_forward_wide_late_none_type;
extern struct LmTestForwardWideLateNone *lm_test_forward_wide_late_none_type;
extern LmTestForwardWideAfterOther *lm_test_forward_wide_after_other_type;
extern struct LmTestForwardWideAfterOther *lm_test_forward_wide_after_other_type;
extern LmTestForwardWideBackendOverlay *lm_test_forward_wide_backend_overlay_type;
extern union LmTestForwardWideBackendOverlay *lm_test_forward_wide_backend_overlay_type;
extern LmTestForwardWidePhysical *lm_test_forward_wide_physical_type;
extern struct LmTestForwardWidePhysical *lm_test_forward_wide_physical_type;
extern LmTestForwardWideJoined *lm_test_forward_wide_joined_type;
extern struct LmTestForwardWideJoined *lm_test_forward_wide_joined_type;
extern LmTestForwardWideSchemaFallback *lm_test_forward_wide_schema_fallback_type;
extern struct LmTestForwardWideSchemaFallback *lm_test_forward_wide_schema_fallback_type;
extern LmTestForwardWideLayout *lm_test_forward_wide_layout_type;
extern struct LmTestForwardWideLayout *lm_test_forward_wide_layout_type;
typedef int LmTestForwardWideOtherOnly;
typedef int LmTestForwardWideNone;

#endif
